### ISSUE TITLE
이전에 썼다 지운 내용이 merge가 되었습니다.

### ISSUE THREAD

**Issue by Wisdom-Kim** [daew0n/cau-osp2020-novel#160]
안녕하세요 20204656김지혜입니다.
다름이 아니라 소설이 얼마 써지지 않았을 때 exposition-02에서 소설 초반에 먹은 참치캔이 다른 고양이의 것이었어서 고양이와 싸우게 되는 장면을 추가했다가 conflict가 되어 다시 업데이트를 하고 참치캔 이야기가 아닌 새로운 내용을 적은 후 다시 pull request를 드렸습니다. (톰과 제리가 조우했을 때 내용을 추가했습니다)
그런데 merge가 되어서 확인해보니 처음에 적었던 참치캔 이야기가 있네요....제가 pull request를 드릴 때 잘못 드린 것 같습니다 수정해주시면 감사하겠습니다

**Comment by Wisdom-Kim** [comment]
아 아닙니다...! 계속 main branch 업데이트 중 conflict가 발생하여 수정을 못했는데 강의를 올려주셨네요 감사합니다 한 번 시도해보겠습니다

**Comment by Namkyunghun** [comment]
revert 하였습니다.
