### ISSUE TITLE
교수님..실수로 main 브랜치를 건드렸습니다.

### ISSUE THREAD

**Issue by Imhanbin123** [daew0n/cau-osp2020-novel#199]
제가 어제 새벽에 작업하다가 실수로 main 브랜치를 수정 후 커밋해버렸습니다. 뭔가 문제가 커질 거 같아서 그 이후로 아무것도 건드린 건 없는데 이런 경우 어떻게 해야 하나요?

**Comment by daew0n** [comment]
슬랙에서 도움 드렸습니다
