### ISSUE TITLE
저장소를 업데이트하는 과정에서 문제가 생겼습니다. 

### ISSUE THREAD

**Issue by Imhanbin123** [daew0n/cau-osp2020-novel#24]
안녕하세요, 교수님. 저는 20200898 한빈입니다. 
교수님께서 주신 링크를 참고해서 저장소를 업데이트하였는데, 클래식 내용 작성하신 분의 글만 반영되고 다른 글은 업데이트가 되지 않고 누락되었습니다. 다시 merge 하기 위해 compare를 누르니까 switch가 되지 않아서 그런데 이런 경우에는 어떻게 해야할까요? ㅠㅠ

**Comment by daew0n** [comment]
슬랙 대화를 통해 잘 해겼습니다 👍
