### ISSUE TITLE
업뎃 후 pull request 부분에 문제가 생겼습니다.

### ISSUE THREAD

**Issue by Eunyoung1223** [daew0n/cau-osp2020-novel#26]
안녕하세요 교수님, 20201192 지은영입니다. 제가 pull request를 안하고 발단 부분 내용을 작성해서 반려된 것 같아 업뎃을 한 후
exposition-20201192-01 기존 브랜치를 삭제하고 다시 이 이름으로 만들어 반영을 했습니다. 다시 작성했던 내용으로 pull request를 하려 하는데 pull requests에 compare&pull request 버튼이 보이지 않고 New pull request만 보여 pull request를 못하고 있는 상황입니다. 문제가 어디에서 발생한 것인지 잘 모르겠습니다..

**Comment by Eunyoung1223** [comment]
방금 new pull request를 하니 다시 버튼이 <code>쪽에 생겨 pull request를 할 수 있었습니다. 문제 해결했습니다!

**Comment by daew0n** [comment]
수고하셨습니다!
