### ISSUE TITLE
20204453 예술공학부 마승환(MaSeongHwan)입니다.

### ISSUE THREAD

**Issue by MaSeongHwan** [daew0n/cau-osp2020-novel#37]
혹시 제가 쓴 글이 등록이 안된건데 등록 절차상 문제인가요 아니면 반려된 건가요??

**Comment by dnalsitresed** [comment]
아이디 MaSeongHwan으로 들어온 리퀘스트가 없습니다. Pull request가 제대로 되지 않은 것 같습니다.
