### ISSUE TITLE
브랜치 삭제 관련 질문입니다.

### ISSUE THREAD

**Issue by imyoumin** [daew0n/cau-osp2020-novel#376]
안녕하십니까 교수님 20201607 임유민 입니다. 다름이 아니라 제가 전에 실험용으로 만든 브렌치를 삭제하는 과정에서 exposition-20201607-01(처음 발단 추가한 브렌치)까지 삭제가 되어버린 듯 합니다. merge는 되긴 했는데, 혹시 이점에 대해서 문제가 있는지 여쭈어 보고 싶습니다!

**Comment by daew0n** [comment]
일단 merge 했기 때문에 괜찮습니다. 되도록 브랜치를 유지해 주셔야 기록이 남으며 나중에 문제가 생기는 경우 증명할 수 있습니다.
