### ISSUE TITLE
[record] 12시 전에 보냈으나 업데이트 되지 않은 부분이 있습니다.

### ISSUE THREAD

**Issue by delight28** [daew0n/cau-osp2020-novel#574]
![image](https://user-images.githubusercontent.com/54145180/99271399-3a054380-286a-11eb-8e3d-b195c5c66c14.png)

여기 7번과 8번 삽화가 merge 되었지만, 
record에서는 12시가 지나도 업데이트가 되지 않았던데... 이런경우는 인정받지 못하나요?

**Comment by daew0n** [comment]
다시 한번 Pull Request 보내주세요
