### ISSUE TITLE
merge 횟수 관련 문의 드립니다!

### ISSUE THREAD

**Issue by yejik1002** [daew0n/cau-osp2020-novel#87]
1인당 한 라운드에서 최대로 merge할 수 있는 횟수가 1)'소설 내용 추가'의 경우에만 최대 3번인 것인지, 2)작성 종류와는 상관 없이 모두 합쳐서 최대 3번인 것인지 궁금합니다. 예를 들어 내용 추가, 정정(띄어쓰기), 삽화내용 추가로 발단 파트에서 3번 merge를 했다면 발단 파트에서는 더 이상 merge를 할 수 없나요?

**Comment by daew0n** [comment]
Merge 횟수는 무한정 하실 수 있고, 채점 과정에서 최대 3회만 인정해 드리는 것입니다.
즉, Merge 횟수에 상관없이 소설을 작성하시고 싶으신 분들은 횟수를 신경 쓰지 않으셔도 됩니다.
